Remove sample/remote-ip_sample2.rb
This doesn't appear to run correctly, even in tk 0.2.0 before the
recent $SAFE removal:

/home/jeremy/tmp/tk/lib/multi-tk.rb:2081:in `method_missing': undefined method `_is_master_of?' for #<RemoteTkIp:0x0000003c9657c5b0> (NoMethodError)

Trying to fix that by removing the protected on the method gives:

/home/jeremy/tmp/tk/lib/multi-tk.rb:2713:in `deleted?': no permission to manipulate (SecurityError)

On exit in both cases, you get:

/home/jeremy/tmp/tk/lib/tk.rb:3013:in `_invoke': can't delete "INTERP_FINALIZE_HOOK": command doesn't exist (RuntimeError)

It's certainly possible these are underlying issues with lib/remote-tk.rb
or lib/multi-tk.rb and not a problem with the sample itself, but I don't
think it's a good idea to ship a sample that is broken.